# ========== FRONTEND TASKS ==========

# Install frontend dependencies - Unix (Linux/macOS)
[tasks.install-frontend-deps-unix]
condition = { platforms = ["linux", "macos"] }
command = "npm"
args = ["install"]
cwd = "./src/frontend"
description = "Install frontend dependencies on Linux/Mac"

# Install frontend dependencies - Windows
[tasks.install-frontend-deps-windows]
condition = { platforms = ["windows"] }
command = "npm.cmd"
args = ["install"]
cwd = "./src/frontend"
description = "Install frontend dependencies on Windows"

# Build React frontend - Unix (Linux/macOS)
[tasks.build-react-unix]
condition = { platforms = ["linux", "macos"] }
command = "npm"
args = ["run", "build"]
cwd = "./src/frontend"
dependencies = ["install-frontend-deps-unix"]
description = "Build the React frontend on Linux/Mac"

# Build React frontend - Windows
[tasks.build-react-windows]
condition = { platforms = ["windows"] }
command = "npm.cmd"
args = ["run", "build"]
cwd = "./src/frontend"
dependencies = ["install-frontend-deps-windows"]
description = "Build the React frontend on Windows"

# Start React dev server - Unix (Linux/macOS)
[tasks.dev-frontend-unix]
condition = { platforms = ["linux", "macos"] }
command = "npm"
args = ["start"]
cwd = "./src/frontend"
dependencies = ["install-frontend-deps-unix"]
description = "Start the React development server on Linux/Mac"

# Start React dev server - Windows
[tasks.dev-frontend-windows]
condition = { platforms = ["windows"] }
command = "npm.cmd"
args = ["start"]
cwd = "./src/frontend"
dependencies = ["install-frontend-deps-windows"]
description = "Start the React development server on Windows"

# Test React frontend - Unix (Linux/macOS)
[tasks.test-frontend-unix]
condition = { platforms = ["linux", "macos"] }
command = "npm"
args = ["test", "--", "--watchAll=false"]
cwd = "./src/frontend"
dependencies = ["install-frontend-deps-unix"]
description = "Run React tests on Linux/Mac"

# Test React frontend - Windows
[tasks.test-frontend-windows]
condition = { platforms = ["windows"] }
command = "npm.cmd"
args = ["test", "--", "--watchAll=false"]
cwd = "./src/frontend"
dependencies = ["install-frontend-deps-windows"]
description = "Run React tests on Windows"

# Clean frontend - Unix (Linux/macOS)
[tasks.clean-frontend-unix]
condition = { platforms = ["linux", "macos"] }
script = [
    "cd src/frontend",
    "rm -rf node_modules build"
]
description = "Clean frontend build artifacts on Linux/Mac"

# Clean frontend - Windows
[tasks.clean-frontend-windows]
condition = { platforms = ["windows"] }
script = [
    "cd src/frontend",
    "rmdir /s /q node_modules 2>nul || echo node_modules not found",
    "rmdir /s /q build 2>nul || echo build not found"
]
description = "Clean frontend build artifacts on Windows"

# ========== CROSS-PLATFORM MAIN TASKS ==========

# Install frontend dependencies (cross-platform)
[tasks.install-frontend-deps]
dependencies = ["install-frontend-deps-unix", "install-frontend-deps-windows"]
description = "Install frontend dependencies (cross-platform)"

# Build React frontend (cross-platform)
[tasks.build-frontend]
dependencies = ["build-react-unix", "build-react-windows"]
description = "Build the React frontend (cross-platform)"

# Start React dev server (cross-platform)
[tasks.dev-frontend]
dependencies = ["dev-frontend-unix", "dev-frontend-windows"]
description = "Start the React development server (cross-platform)"

# Test React frontend (cross-platform)
[tasks.test-frontend]
dependencies = ["test-frontend-unix", "test-frontend-windows"]
description = "Run React tests (cross-platform)"

# Clean frontend (cross-platform)
[tasks.clean-frontend]
dependencies = ["clean-frontend-unix", "clean-frontend-windows"]
description = "Clean frontend build artifacts (cross-platform)"

# ========== MAIN BUILD TASKS ==========

# Build everything: frontend + backend
[tasks.build-all]
dependencies = ["build-frontend", "build"]
description = "Build both React frontend and Rust backend"

# Development: build frontend and run server
[tasks.dev]
dependencies = ["build-frontend"]
run_task = "run"
description = "Build frontend and run the Rust server"

# Clean everything: frontend + backend
[tasks.clean-all]
dependencies = ["clean-frontend", "clean"]
description = "Clean both frontend and backend build artifacts"

# Show available tasks
[tasks.help]
script = [
    "echo Available tasks:",
    "echo   build-all      - Build frontend and backend",
    "echo   build-frontend - Build only the React frontend",
    "echo   dev            - Build frontend and start server",
    "echo   dev-frontend   - Start React dev server only",
    "echo   test-frontend  - Run React tests",
    "echo   clean-all      - Clean everything",
    "echo   clean-frontend - Clean only frontend"
]
description = "Show available tasks"